export const inputTableHead = ["PID", "Arrival time", "Burst Time", "Priority"];
export const outputTableHead = ["Completion Time","TurnAround Time","Waiting Time"];
export const SchedulingTypes = ["FCFS", "SRTF", "PRIORITY", "ROUNDROBIN"];
export const colors = ["#1b8c5c", "#f8b005", "#9c2a2f", "#536878"];
export const bankersTableHead=["PID","A","B","C"]
export const bankersOutPutTableHead=["A","B","C"]
export const Available=["A","B","C"]
export const BankersMssg="The banker’s algorithm is a resource allocation and deadlock avoidance algorithm that tests for safety by simulating the allocation for predetermined maximum possible amounts of all resources, then makes an “s-state” check to test for possible activities, before deciding whether allocation should be allowed to continue."
export const SchedulerMssg=" The main task of CPU scheduling is to make sure that whenever the CPU remains idle, the OS at least select one of the processes available in the ready queue for execution. The selection process will be carried out by the CPU scheduler. It selects one of the processes in memory that are ready for execution."